# Generated by Django 5.2.12 on 2026-04-09 08:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='Category image'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='Gallery image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, verbose_name='Product image'),
        ),
    ]
